# Generated by Django 4.2.7 on 2024-02-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_image_alter_userprofile_bloodgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/images/'),
        ),
    ]
